apiVersion: v1
kind: Template
metadata:
  name: promtail
  annotations:
    "openshift.io/display-name": Loki - promtail
    description: |
      A Logging solution for an OpenShift cluster - collect and gather logs.
    iconClass: fa fa-cogs
    tags: "Logging, Loki, promtail, time-series"
parameters:
  - name: APP_NAME
    description: "Value for app label."
    required: true
 
  - name: NAME_SPACE
    description: "The name of the namespace (openshift project)"
 
  - name: REPLICAS
    description: "number of promtail replicas"
 
objects:
 
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
    namespace: "${NAME_SPACE}"
  spec:
    replicas: ${REPLICAS}
    selector:
      app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
        name: ${APP_NAME}
        annotations:
          prometheus.io/scrape: "true"
          #prometheus.io/port: "3101"
          prometheus.io/path: "/metrics"
      spec:
        containers:
          - name: promtail
            image: grafana/promtail:2.1.0
            args:
              - -config.file=/etc/promtail/promtail.yaml
            resources:
              limits:
                cpu: "500m"
                memory: "128Mi"
              requests:
                cpu: "250m"
                memory: "64Mi"
            ports:
              - name: metrics
                containerPort: 3101
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ready
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 1
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ready
                port: metrics
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 1
            volumeMounts:
              - name: log-data-volume
                mountPath: /app/log
              - name: promtail-config-volume
                mountPath: /etc/promtail
        volumes:
          - name: log-data-volume
            persistentVolumeClaim:
              claimName: log-data
          - name: promtail-config-volume
            configMap:
              defaultMode: 420
              name: promtail-config
 
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: promtail-config
  data:
      promtail.yaml: |-
        server:
            http_listen_port: 3101
        clients:
          - url: http://loki-demo-app.org.com/loki/api/v1/push 
            tenant_id: Demo
        positions:
            filename: /app/log/positions.yaml
        target_config:
            sync_period: 10s
 
        scrape_configs:
          - job_name: boot-prometheus
            static_configs:
              - targets:
                  - localhost
                labels:
                  job: boot-prometheus
                  __path__: /app/log/boot-prometheus*.log
